#!/usr/bin/python
import os, sys
for file in sys.argv[1:]:
    filename = os.path.realpath(file)
    print "exporting %s --> %s" % (filename, file + '.pdf')
    os.system('soffice -headless "macro:///exporter.Module1.Export2PDF(%s)"' % filename)
